/// Application-owned playback manifest (YXZ Tube architecture §5).
///
/// Flutter never sees raw yt-dlp client names or PO tokens — only this schema.
library;

/// How media is delivered to the player.
enum PlaybackDeliveryType {
  /// DASH MPD (reserved; Media3 path later).
  dash,

  /// HLS m3u8.
  hls,

  /// Separate direct video + audio HTTPS URLs.
  adaptiveDirect,

  /// Single muxed progressive file.
  progressive,
}

/// Parses delivery type from server JSON (`direct` → [adaptiveDirect]).
PlaybackDeliveryType playbackDeliveryTypeFromJson(String? raw) {
  switch ((raw ?? '').toLowerCase()) {
    case 'dash':
      return PlaybackDeliveryType.dash;
    case 'hls':
      return PlaybackDeliveryType.hls;
    case 'direct':
    case 'adaptive':
    case 'adaptive_direct':
    case 'adaptivedirect':
      return PlaybackDeliveryType.adaptiveDirect;
    case 'progressive':
    default:
      return PlaybackDeliveryType.progressive;
  }
}

/// One video representation in a [PlaybackManifest].
class VideoRepresentation {
  /// Creates a video representation.
  const VideoRepresentation({
    required this.id,
    required this.url,
    required this.height,
    required this.isVideoOnly,
    this.width,
    this.fps,
    this.bitrate,
    this.codec,
    this.mimeType,
    this.ext,
    this.hdr = false,
  });

  /// Format / itag id.
  final String id;

  /// Direct HTTPS media URL.
  final String url;

  /// Pixel height.
  final int height;

  /// Pixel width when known.
  final int? width;

  /// Frames per second when known.
  final int? fps;

  /// Approximate bitrate (bits/sec or yt-dlp tbr*1000).
  final int? bitrate;

  /// Codec string (e.g. `avc1`).
  final String? codec;

  /// MIME type when known.
  final String? mimeType;

  /// Container extension.
  final String? ext;

  /// True when this stream has no audio track.
  final bool isVideoOnly;

  /// HDR signal when known.
  final bool hdr;

  /// True when codec looks like H.264.
  bool get isH264 {
    final String c = (codec ?? '').toLowerCase();
    return c.contains('avc') || c.contains('h264');
  }

  /// Parses a stream object from JSON.
  factory VideoRepresentation.fromJson(Map<String, dynamic> json) {
    return VideoRepresentation(
      id: json['id']?.toString() ?? '',
      url: json['url']?.toString() ?? '',
      height: _asInt(json['height']) ?? 0,
      width: _asInt(json['width']),
      fps: _asInt(json['fps']),
      bitrate: _asInt(json['bitrate']),
      codec: json['codec']?.toString(),
      mimeType: json['mimeType']?.toString(),
      ext: json['ext']?.toString(),
      isVideoOnly: json['isVideoOnly'] == true,
      hdr: json['hdr'] == true,
    );
  }
}

/// One audio representation in a [PlaybackManifest].
class AudioRepresentation {
  /// Creates an audio representation.
  const AudioRepresentation({
    required this.id,
    required this.url,
    this.bitrate,
    this.codec,
    this.mimeType,
    this.ext,
    this.sampleRate,
    this.channels,
  });

  /// Format / itag id.
  final String id;

  /// Direct HTTPS media URL.
  final String url;

  /// Approximate bitrate.
  final int? bitrate;

  /// Codec string (e.g. `mp4a`).
  final String? codec;

  /// MIME type when known.
  final String? mimeType;

  /// Container extension.
  final String? ext;

  /// Sample rate Hz.
  final int? sampleRate;

  /// Channel count.
  final int? channels;

  /// Prefer m4a / mp4a for media_kit.
  bool get prefersMp4a {
    final String c = (codec ?? '').toLowerCase();
    final String e = (ext ?? '').toLowerCase();
    return c.contains('mp4a') || e == 'm4a' || e == 'mp4';
  }

  /// Parses an audio stream from JSON.
  factory AudioRepresentation.fromJson(Map<String, dynamic> json) {
    return AudioRepresentation(
      id: json['id']?.toString() ?? '',
      url: json['url']?.toString() ?? '',
      bitrate: _asInt(json['bitrate']),
      codec: json['codec']?.toString(),
      mimeType: json['mimeType']?.toString(),
      ext: json['ext']?.toString(),
      sampleRate: _asInt(json['sampleRate']),
      channels: _asInt(json['channels']),
    );
  }
}

/// Subtitle track metadata (URLs optional in this milestone).
class SubtitleRepresentation {
  /// Creates a subtitle row.
  const SubtitleRepresentation({
    required this.language,
    this.url,
    this.isAutoGenerated = false,
  });

  /// BCP-47 / yt-dlp language code.
  final String language;

  /// Subtitle file URL when available.
  final String? url;

  /// Auto-caption flag.
  final bool isAutoGenerated;

  /// Parses subtitle JSON.
  factory SubtitleRepresentation.fromJson(Map<String, dynamic> json) {
    return SubtitleRepresentation(
      language: json['language']?.toString() ?? '',
      url: json['url']?.toString(),
      isAutoGenerated: json['isAutoGenerated'] == true,
    );
  }
}

/// Delivery hint for the player (DASH/HLS URL or direct streams).
class PlaybackDelivery {
  /// Creates a delivery block.
  const PlaybackDelivery({
    required this.type,
    this.manifestUrl,
  });

  /// Delivery mode.
  final PlaybackDeliveryType type;

  /// DASH/HLS manifest URL when [type] is dash/hls.
  final String? manifestUrl;

  /// Parses delivery JSON.
  factory PlaybackDelivery.fromJson(Map<String, dynamic> json) {
    return PlaybackDelivery(
      type: playbackDeliveryTypeFromJson(json['type']?.toString()),
      manifestUrl: json['manifestUrl']?.toString(),
    );
  }
}

/// Server quality selection contract.
class PlaybackQualityContract {
  /// Creates the contract.
  const PlaybackQualityContract({
    required this.requestedQuality,
    required this.selectedQuality,
    this.qualityFallback = false,
    this.fallbackReason,
  });

  /// Client-requested quality label.
  final String requestedQuality;

  /// Server-selected quality label.
  final String selectedQuality;

  /// True when selected is below requested.
  final bool qualityFallback;

  /// Machine reason when [qualityFallback] is true.
  final String? fallbackReason;

  /// Parses contract JSON.
  factory PlaybackQualityContract.fromJson(Map<String, dynamic> json) {
    return PlaybackQualityContract(
      requestedQuality: json['requestedQuality']?.toString() ?? 'auto',
      selectedQuality: json['selectedQuality']?.toString() ?? 'auto',
      qualityFallback: json['qualityFallback'] == true,
      fallbackReason: json['fallbackReason']?.toString(),
    );
  }
}

/// Normalized playback payload — extractor-agnostic.
class PlaybackManifest {
  /// Creates a manifest.
  const PlaybackManifest({
    required this.schemaVersion,
    required this.videoId,
    required this.title,
    required this.source,
    required this.delivery,
    required this.videoStreams,
    required this.audioStreams,
    required this.headers,
    this.durationMs,
    this.expiresAt,
    this.subtitles = const <SubtitleRepresentation>[],
    this.uploader,
    this.thumbnail,
    this.webpageUrl,
    this.quality,
  });

  /// Schema version (currently `1`).
  final int schemaVersion;

  /// YouTube video id.
  final String videoId;

  /// Display title.
  final String title;

  /// Extractor source label (`youtube`).
  final String source;

  /// Preferred delivery description.
  final PlaybackDelivery delivery;

  /// Video representations (adaptive + progressive).
  final List<VideoRepresentation> videoStreams;

  /// Audio-only representations.
  final List<AudioRepresentation> audioStreams;

  /// HTTP headers for CDN fetches.
  final Map<String, String> headers;

  /// Duration in milliseconds.
  final int? durationMs;

  /// Earliest stream URL expiry.
  final DateTime? expiresAt;

  /// Subtitle tracks.
  final List<SubtitleRepresentation> subtitles;

  /// Channel name.
  final String? uploader;

  /// Thumbnail URL.
  final String? thumbnail;

  /// Canonical watch URL.
  final String? webpageUrl;

  /// Optional quality contract from server.
  final PlaybackQualityContract? quality;

  /// Distinct heights with a direct HTTP video URL.
  List<int> get availableHeights {
    final Set<int> heights = <int>{};
    for (final VideoRepresentation v in videoStreams) {
      if (v.height > 0) {
        heights.add(v.height);
      }
    }
    final List<int> sorted = heights.toList()..sort();
    return sorted;
  }

  /// Video-only adaptive rows.
  List<VideoRepresentation> get adaptiveVideo => videoStreams
      .where((VideoRepresentation v) => v.isVideoOnly)
      .toList(growable: false);

  /// Muxed progressive rows.
  List<VideoRepresentation> get progressiveVideo => videoStreams
      .where((VideoRepresentation v) => !v.isVideoOnly)
      .toList(growable: false);

  /// True when any playable representation exists.
  bool get isPlayable =>
      delivery.manifestUrl != null ||
      adaptiveVideo.isNotEmpty && audioStreams.isNotEmpty ||
      progressiveVideo.isNotEmpty;

  /// Parses server or builder JSON (flat or nested `video` block).
  factory PlaybackManifest.fromJson(Map<String, dynamic> json) {
    final Map<String, dynamic>? videoNested = json['video'] is Map
        ? Map<String, dynamic>.from(json['video'] as Map)
        : null;
    final String videoId =
        json['videoId']?.toString() ?? videoNested?['id']?.toString() ?? '';
    final String title =
        json['title']?.toString() ?? videoNested?['title']?.toString() ?? '';
    final Map<String, String> headers = <String, String>{};
    final Object? rawHeaders = json['headers'];
    if (rawHeaders is Map) {
      rawHeaders.forEach((Object? k, Object? v) {
        if (k != null && v != null) {
          headers[k.toString()] = v.toString();
        }
      });
    }
    final List<VideoRepresentation> videos = <VideoRepresentation>[];
    final Object? rawVideos = json['videoStreams'];
    if (rawVideos is List) {
      for (final Object? row in rawVideos) {
        if (row is Map) {
          videos.add(
            VideoRepresentation.fromJson(Map<String, dynamic>.from(row)),
          );
        }
      }
    }
    final List<AudioRepresentation> audios = <AudioRepresentation>[];
    final Object? rawAudios = json['audioStreams'];
    if (rawAudios is List) {
      for (final Object? row in rawAudios) {
        if (row is Map) {
          audios.add(
            AudioRepresentation.fromJson(Map<String, dynamic>.from(row)),
          );
        }
      }
    }
    final List<SubtitleRepresentation> subs = <SubtitleRepresentation>[];
    final Object? rawSubs = json['subtitles'];
    if (rawSubs is List) {
      for (final Object? row in rawSubs) {
        if (row is Map) {
          subs.add(
            SubtitleRepresentation.fromJson(Map<String, dynamic>.from(row)),
          );
        }
      }
    }
    final Object? deliveryRaw = json['delivery'];
    final PlaybackDelivery delivery = deliveryRaw is Map
        ? PlaybackDelivery.fromJson(Map<String, dynamic>.from(deliveryRaw))
        : const PlaybackDelivery(type: PlaybackDeliveryType.progressive);
    final Object? qualityRaw = json['quality'];
    return PlaybackManifest(
      schemaVersion: _asInt(json['schemaVersion']) ?? 1,
      videoId: videoId,
      title: title,
      source: json['source']?.toString() ?? 'youtube',
      delivery: delivery,
      videoStreams: videos,
      audioStreams: audios,
      headers: headers,
      durationMs:
          _asInt(json['durationMs']) ?? _asInt(videoNested?['durationMs']),
      expiresAt: _asDate(json['expiresAt']),
      subtitles: subs,
      uploader:
          json['uploader']?.toString() ?? videoNested?['uploader']?.toString(),
      thumbnail: json['thumbnail']?.toString() ??
          videoNested?['thumbnail']?.toString(),
      webpageUrl: json['webpageUrl']?.toString() ??
          videoNested?['webpageUrl']?.toString(),
      quality: qualityRaw is Map
          ? PlaybackQualityContract.fromJson(
              Map<String, dynamic>.from(qualityRaw),
            )
          : null,
    );
  }
}

int? _asInt(Object? value) {
  if (value is int) {
    return value;
  }
  if (value is num) {
    return value.round();
  }
  return int.tryParse(value?.toString() ?? '');
}

DateTime? _asDate(Object? value) {
  if (value == null) {
    return null;
  }
  return DateTime.tryParse(value.toString());
}
