/** Typed API / extractor error codes (README §23). */
export const ErrorCodes = {
  EXTRACTOR_TIMEOUT: 'EXTRACTOR_TIMEOUT',
  EXTRACTOR_NO_STREAM: 'EXTRACTOR_NO_STREAM',
  EXTRACTOR_PO_TOKEN_REQUIRED: 'EXTRACTOR_PO_TOKEN_REQUIRED',
  EXTRACTOR_JS_RUNTIME_ERROR: 'EXTRACTOR_JS_RUNTIME_ERROR',
  EXTRACTOR_RATE_LIMITED: 'EXTRACTOR_RATE_LIMITED',
  EXTRACTOR_VIDEO_UNAVAILABLE: 'EXTRACTOR_VIDEO_UNAVAILABLE',
  EXTRACTOR_PRIVATE: 'EXTRACTOR_PRIVATE',
  EXTRACTOR_GEO_BLOCKED: 'EXTRACTOR_GEO_BLOCKED',
  EXTRACTOR_CHALLENGE_FAILED: 'EXTRACTOR_CHALLENGE_FAILED',
  EXTRACTOR_UPSTREAM_CHANGED: 'EXTRACTOR_UPSTREAM_CHANGED',
  PLAYBACK_STREAM_EXPIRED: 'PLAYBACK_STREAM_EXPIRED',
  PLAYBACK_403: 'PLAYBACK_403',
  PLAYBACK_410: 'PLAYBACK_410',
  PLAYBACK_UNSUPPORTED_CODEC: 'PLAYBACK_UNSUPPORTED_CODEC',
  PLAYBACK_NETWORK_ERROR: 'PLAYBACK_NETWORK_ERROR',
  PLAYBACK_PREPARE_FAILED: 'PLAYBACK_PREPARE_FAILED',
  QUALITY_UNAVAILABLE: 'QUALITY_UNAVAILABLE',
  AUTH_INVALID: 'AUTH_INVALID',
  AUTH_EXPIRED: 'AUTH_EXPIRED',
  AUTH_REVOKED: 'AUTH_REVOKED',
  RATE_LIMITED: 'RATE_LIMITED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

/** Errors that must NOT fall back to local client extraction. */
export const NON_FALLBACK_CODES: ReadonlySet<string> = new Set([
  ErrorCodes.EXTRACTOR_VIDEO_UNAVAILABLE,
  ErrorCodes.EXTRACTOR_PRIVATE,
  ErrorCodes.EXTRACTOR_GEO_BLOCKED,
  ErrorCodes.EXTRACTOR_CHALLENGE_FAILED,
  ErrorCodes.AUTH_REVOKED,
]);

export function isRestrictedError(code: string | undefined): boolean {
  if (!code) return false;
  return NON_FALLBACK_CODES.has(code);
}
