import { z } from 'zod';

export const DeliveryTypeSchema = z.enum([
  'adaptive',
  'direct',
  'progressive',
  'hls',
  'dash',
]);

export const VideoStreamSchema = z.object({
  id: z.string(),
  url: z.string().url(),
  height: z.number().int().positive(),
  width: z.number().int().positive().optional(),
  fps: z.number().optional(),
  bitrate: z.number().optional(),
  codec: z.string().optional(),
  mimeType: z.string().optional(),
  ext: z.string().optional(),
  isVideoOnly: z.boolean(),
  hdr: z.boolean().default(false),
  expiresAt: z.string().datetime().optional(),
});

export const AudioStreamSchema = z.object({
  id: z.string(),
  url: z.string().url(),
  bitrate: z.number().optional(),
  codec: z.string().optional(),
  mimeType: z.string().optional(),
  ext: z.string().optional(),
  sampleRate: z.number().optional(),
  channels: z.number().optional(),
  expiresAt: z.string().datetime().optional(),
});

export const SubtitleSchema = z.object({
  language: z.string(),
  url: z.string().url().optional(),
  isAutoGenerated: z.boolean().default(false),
});

export const QualityContractSchema = z.object({
  requestedQuality: z.string(),
  selectedQuality: z.string(),
  qualityFallback: z.boolean().default(false),
});

export const PlaybackManifestSchema = z.object({
  schemaVersion: z.literal(1),
  videoId: z.string().min(1),
  title: z.string(),
  source: z.string().default('youtube'),
  durationMs: z.number().int().nonnegative().optional(),
  resolvedAt: z.string().datetime(),
  expiresAt: z.string().datetime().optional(),
  delivery: z.object({
    type: DeliveryTypeSchema,
    manifestUrl: z.string().url().optional(),
  }),
  videoStreams: z.array(VideoStreamSchema),
  audioStreams: z.array(AudioStreamSchema),
  subtitles: z.array(SubtitleSchema).default([]),
  headers: z.record(z.string()).default({}),
  uploader: z.string().optional(),
  thumbnail: z.string().optional(),
  webpageUrl: z.string().optional(),
  quality: QualityContractSchema.optional(),
});

export type PlaybackManifest = z.infer<typeof PlaybackManifestSchema>;
export type VideoStream = z.infer<typeof VideoStreamSchema>;
export type AudioStream = z.infer<typeof AudioStreamSchema>;
export type DeliveryType = z.infer<typeof DeliveryTypeSchema>;

export const PlaybackQuerySchema = z.object({
  quality: z
    .enum(['auto', '360p', '480p', '720p', '1080p', '1440p', '2160p'])
    .default('auto'),
  codec: z.enum(['auto', 'avc1', 'vp9', 'av01']).default('auto'),
  audioLanguage: z.string().default('auto'),
  hdr: z.enum(['auto', 'sdr', 'hdr']).default('auto'),
  forceRefresh: z
    .union([z.literal('true'), z.literal('false'), z.boolean()])
    .optional()
    .transform((v) => v === true || v === 'true'),
});

export type PlaybackQuery = z.infer<typeof PlaybackQuerySchema>;

export const VideoIdSchema = z
  .string()
  .regex(/^[A-Za-z0-9_-]{6,20}$/, 'Invalid YouTube video id');

export const CreateDownloadSchema = z.object({
  videoId: VideoIdSchema,
  quality: z
    .enum(['360p', '480p', '720p', '1080p', '1440p', '2160p', 'best'])
    .default('1080p'),
  format: z.enum(['mp4', 'webm', 'audio']).default('mp4'),
});

export type CreateDownload = z.infer<typeof CreateDownloadSchema>;

export const DownloadJobStatusSchema = z.enum([
  'queued',
  'running',
  'completed',
  'failed',
  'cancelled',
]);

export type DownloadJobStatus = z.infer<typeof DownloadJobStatusSchema>;
